<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="XiaoK.Tools.SafetyChecks" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XiaoK.Core\XiaoK.Core.csproj" />
    <PackageReference Include="PdfPig" Version="[0.1.16]" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
